"""
Tax God - Tax Writer Service
Generates professional tax memoranda, client letters, and advisory documents.

Document Types:
  1. Tax Research Memorandum (formal IRAC analysis)
  2. Client Advisory Letter (plain-language advice)
  3. Position Summary (audit defense documentation)
  4. Tax Planning Report (multi-year strategy)
  5. Engagement Letter (scope & terms)

All documents include:
  - Proper legal citations (IRC, Treas. Reg., case law)
  - Professional disclaimers
  - Date stamps and version tracking
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import Enum

from app.services.ai_service import AIOrchestrator
from app.services.citation_engine import CitationEngine

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Document Types & Templates
# ---------------------------------------------------------------------------


class DocumentType(str, Enum):
    TAX_MEMO = "tax_research_memo"
    CLIENT_LETTER = "client_advisory_letter"
    POSITION_SUMMARY = "position_summary"
    PLANNING_REPORT = "tax_planning_report"
    ENGAGEMENT_LETTER = "engagement_letter"
    AUDIT_RESPONSE = "audit_response_letter"


@dataclass
class GeneratedDocument:
    """A document produced by Tax Writer."""

    document_id: str
    document_type: DocumentType
    title: str
    content: str  # Full formatted text
    sections: list[dict[str, str]]  # structured sections
    citations: list[dict[str, str]]  # cited authorities
    client_id: str = ""
    tax_year: int = 2024
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    model_used: str = ""
    confidence: float = 0.0
    word_count: int = 0
    disclaimer: str = ""


# ---------------------------------------------------------------------------
# Memo Templates (IRAC Structure)
# ---------------------------------------------------------------------------

MEMO_TEMPLATE = """
TAX RESEARCH MEMORANDUM
=======================

Date:        {date}
To:          {client_name}
From:        Tax God AI Advisory
Re:          {subject}
Tax Year:    {tax_year}

DISCLAIMER: This memorandum is for informational purposes only and does not
constitute legal or tax advice. Please consult with a licensed tax professional
or attorney before taking any action based on this analysis.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

I. ISSUE(S) PRESENTED
─────────────────────
{issues}

II. SHORT ANSWER
────────────────
{short_answer}

III. FACTS
──────────
{facts}

IV. ANALYSIS
────────────
{analysis}

V. CONCLUSION & RECOMMENDATIONS
────────────────────────────────
{conclusion}

VI. AUTHORITIES CITED
─────────────────────
{authorities}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

CONFIDENTIALITY NOTICE: This document contains confidential information
intended only for the named recipient(s). Unauthorized disclosure is prohibited.

Generated by Tax God AI Advisory System v3.0
"""

CLIENT_LETTER_TEMPLATE = """
{firm_name}
{date}

{client_name}
{client_address}

Dear {client_salutation},

Re: {subject}

{body}

Next Steps:
{next_steps}

Please do not hesitate to contact us if you have questions about the above.

This letter is for informational purposes only and does not constitute legal
or tax advice. We recommend consulting with a licensed professional before
taking action.

Respectfully,

Tax God AI Advisory
"""

AUDIT_RESPONSE_TEMPLATE = """
{date}

Internal Revenue Service
{irs_office}
{irs_address}

Re:     {taxpayer_name}
        {taxpayer_ssn_masked}
        Tax Year(s): {tax_years}
        Notice/Case Number: {case_number}

Dear Examiner:

This letter is submitted in response to your {notice_type} dated {notice_date}.

{response_body}

SUPPORTING DOCUMENTATION
{documentation_list}

LEGAL AUTHORITIES
{authorities}

We respectfully request that you consider the above information and adjust
the proposed assessment accordingly.

Sincerely,

{preparer_name}
Tax God AI Advisory (Prepared for review by licensed representative)

Enclosures: {enclosure_count}
"""


# ---------------------------------------------------------------------------
# Tax Writer Service
# ---------------------------------------------------------------------------


class TaxWriter:
    """
    Generates professional tax documents using AI + citation engine.
    """

    def __init__(
        self,
        ai_orchestrator: AIOrchestrator | None = None,
        citation_engine: CitationEngine | None = None,
    ):
        self.ai = ai_orchestrator
        self.citations = citation_engine or CitationEngine()

    async def generate_tax_memo(
        self,
        subject: str,
        facts: str,
        client_name: str = "Client",
        client_id: str = "",
        tax_year: int = 2024,
        additional_context: str = "",
    ) -> GeneratedDocument:
        """
        Generate a formal Tax Research Memorandum using IRAC structure.
        (Issue, Rule, Application, Conclusion)
        """
        import uuid

        # Search for relevant citations
        citation_results = self.citations.search(subject + " " + facts, max_results=8)

        authorities_text = "\n".join(
            f"  - {self.citations.format_citation(c, style='full')}" for c in citation_results.citations
        )

        # Build the AI prompt for memo generation
        prompt = (
            f"Write a professional Tax Research Memorandum in IRAC format.\n\n"
            f"SUBJECT: {subject}\n"
            f"FACTS: {facts}\n"
            f"TAX YEAR: {tax_year}\n"
            f"{'ADDITIONAL CONTEXT: ' + additional_context if additional_context else ''}\n\n"
            f"RELEVANT AUTHORITIES (use these and any others applicable):\n{authorities_text}\n\n"
            f"FORMAT:\n"
            f"1. ISSUE(S) PRESENTED - Frame the specific tax question(s)\n"
            f"2. SHORT ANSWER - Direct answer in 2-3 sentences\n"
            f"3. ANALYSIS - Detailed IRAC analysis with specific IRC citations, "
            f"Treasury Regulation references, and relevant case law. Show how the "
            f"law applies to these specific facts.\n"
            f"4. CONCLUSION & RECOMMENDATIONS - Actionable next steps\n\n"
            f"Use precise legal citations throughout (IRC §, Treas. Reg. §, etc.)."
        )

        # Generate via AI
        sections = {}
        content = ""
        model_used = ""
        confidence = 0.0

        if self.ai:
            response = await self.ai.query(
                query=prompt,
                client_id=client_id,
                task_type="memo_writing",
            )
            content = response.content
            model_used = response.model_used
            confidence = response.confidence

            # Parse sections from AI response
            sections = self._parse_memo_sections(content)
        else:
            sections = {
                "issues": f"Whether {subject}",
                "short_answer": "[AI service not available - placeholder]",
                "facts": facts,
                "analysis": "[Requires AI service for analysis]",
                "conclusion": "[Requires AI service for conclusion]",
            }

        # Enrich with verified citations
        enriched = self.citations.enrich_response(content, subject)

        # Format the final memo
        formatted = MEMO_TEMPLATE.format(
            date=datetime.now(UTC).strftime("%B %d, %Y"),
            client_name=client_name,
            subject=subject,
            tax_year=tax_year,
            issues=sections.get("issues", ""),
            short_answer=sections.get("short_answer", ""),
            facts=sections.get("facts", facts),
            analysis=sections.get("analysis", content),
            conclusion=sections.get("conclusion", ""),
            authorities=authorities_text,
        )

        return GeneratedDocument(
            document_id=str(uuid.uuid4()),
            document_type=DocumentType.TAX_MEMO,
            title=f"Tax Research Memo: {subject}",
            content=formatted,
            sections=[{"name": k, "content": v} for k, v in sections.items()],
            citations=enriched.get("verified_citations", []),
            client_id=client_id,
            tax_year=tax_year,
            model_used=model_used,
            confidence=confidence,
            word_count=len(formatted.split()),
            disclaimer="This memorandum is for informational purposes only and does not constitute legal or tax advice.",
        )

    async def generate_client_letter(
        self,
        subject: str,
        key_points: list[str],
        client_name: str,
        client_id: str = "",
        tax_year: int = 2024,
    ) -> GeneratedDocument:
        """Generate a plain-language client advisory letter."""
        import uuid

        points_text = "\n".join(f"  - {p}" for p in key_points)

        prompt = (
            f"Write a professional client advisory letter about: {subject}\n\n"
            f"Key points to cover:\n{points_text}\n\n"
            f"Write in clear, plain language (avoid excessive jargon). "
            f"Include specific IRC citations where relevant but explain them simply. "
            f"End with clear next steps the client should take."
        )

        content = ""
        model_used = ""
        confidence = 0.0

        if self.ai:
            response = await self.ai.query(
                query=prompt,
                client_id=client_id,
                task_type="memo_writing",
            )
            content = response.content
            model_used = response.model_used
            confidence = response.confidence

        formatted = CLIENT_LETTER_TEMPLATE.format(
            firm_name="Tax God AI Advisory",
            date=datetime.now(UTC).strftime("%B %d, %Y"),
            client_name=client_name,
            client_address="[Address on file]",
            client_salutation=client_name.split()[0] if client_name else "Client",
            subject=subject,
            body=content,
            next_steps=points_text,
        )

        return GeneratedDocument(
            document_id=str(uuid.uuid4()),
            document_type=DocumentType.CLIENT_LETTER,
            title=f"Advisory Letter: {subject}",
            content=formatted,
            sections=[{"name": "body", "content": content}],
            citations=[],
            client_id=client_id,
            tax_year=tax_year,
            model_used=model_used,
            confidence=confidence,
            word_count=len(formatted.split()),
        )

    async def generate_audit_response(
        self,
        notice_type: str,
        case_number: str,
        notice_date: str,
        issues: list[str],
        taxpayer_name: str,
        tax_years: str,
        supporting_facts: str,
        client_id: str = "",
    ) -> GeneratedDocument:
        """Generate an IRS audit response letter."""
        import uuid

        issues_text = "\n".join(f"  {i + 1}. {issue}" for i, issue in enumerate(issues))

        prompt = (
            f"Write a professional IRS audit response letter.\n\n"
            f"Notice type: {notice_type}\n"
            f"Issues raised:\n{issues_text}\n"
            f"Supporting facts: {supporting_facts}\n\n"
            f"For each issue:\n"
            f"1. State the taxpayer's position clearly\n"
            f"2. Cite the specific IRC section, Treasury Regulation, or case law that supports the position\n"
            f"3. Explain how the facts satisfy the legal requirements\n"
            f"4. Reference supporting documentation\n\n"
            f"Use professional, respectful tone. Be thorough but concise."
        )

        content = ""
        model_used = ""
        confidence = 0.0

        if self.ai:
            response = await self.ai.query(
                query=prompt,
                client_id=client_id,
                task_type="audit_response",
            )
            content = response.content
            model_used = response.model_used
            confidence = response.confidence

        citation_results = self.citations.search(" ".join(issues), max_results=5)
        authorities_text = "\n".join(
            f"  - {self.citations.format_citation(c, style='full')}" for c in citation_results.citations
        )

        formatted = AUDIT_RESPONSE_TEMPLATE.format(
            date=datetime.now(UTC).strftime("%B %d, %Y"),
            irs_office="[IRS Office]",
            irs_address="[Address per notice]",
            taxpayer_name=taxpayer_name,
            taxpayer_ssn_masked="XXX-XX-XXXX",
            tax_years=tax_years,
            case_number=case_number,
            notice_type=notice_type,
            notice_date=notice_date,
            response_body=content,
            documentation_list="[See enclosed documents]",
            authorities=authorities_text,
            preparer_name="[Licensed Representative Name]",
            enclosure_count="[TBD]",
        )

        return GeneratedDocument(
            document_id=str(uuid.uuid4()),
            document_type=DocumentType.AUDIT_RESPONSE,
            title=f"Audit Response: {notice_type} - {case_number}",
            content=formatted,
            sections=[{"name": "response", "content": content}],
            citations=[{"reference": c.reference, "title": c.title} for c in citation_results.citations],
            client_id=client_id,
            model_used=model_used,
            confidence=confidence,
            word_count=len(formatted.split()),
            disclaimer="This response must be reviewed and signed by a licensed tax professional before submission to the IRS.",
        )

    # -- Helpers ---------------------------------------------------------------

    def _parse_memo_sections(self, content: str) -> dict[str, str]:
        """Parse AI-generated memo content into structured sections."""
        sections: dict[str, str] = {}
        current_section = "analysis"
        current_text: list[str] = []

        section_markers = {
            "issue": "issues",
            "short answer": "short_answer",
            "fact": "facts",
            "analysis": "analysis",
            "conclusion": "conclusion",
            "recommendation": "conclusion",
            "authorit": "authorities",
        }

        for line in content.split("\n"):
            line_lower = line.strip().lower()
            matched = False
            for marker, section_key in section_markers.items():
                if marker in line_lower and (
                    line_lower.startswith(("i.", "ii.", "iii.", "iv.", "v.", "vi.", "#"))
                    or line_lower.startswith(marker)
                ):
                    if current_text:
                        sections[current_section] = "\n".join(current_text).strip()
                    current_section = section_key
                    current_text = []
                    matched = True
                    break
            if not matched:
                current_text.append(line)

        if current_text:
            sections[current_section] = "\n".join(current_text).strip()

        return sections
